### ISSUE TITLE
Support invoking from code

### ISSUE THREAD

**Issue by lebbe** [mifi/stacktracify#12]
I need something very similar, but to use in javascript/typescript itself.

Scenario: I have a serverside express API, with an endpoint that logs errors from frontend (/api/log/). I send a JSON-string of the whole error-object to this endpoint. I would like the express server to "stacktracify" the error.stack and error.componentStack, before logging it further.

If this sounds like a good idea, I could try help get that kind of functionality into this repo, instead of creating yet another repo/application that demystifies stack traces?

(I guess it would involve making a different "bin"-file for the current functionality, and esm-export a function from the index-file. Or change "main" from index.js to another file exporting the core functionality.)

**Comment by mifi** [comment]
not sure but I think the code for stacktracify is so simple that I don't know if it makes sense to abstract it into an API:
https://github.com/mifi/stacktracify/blob/master/index.js

**Comment by lebbe** [comment]
I have already introduced our own "stacktracify", inspired by your great work here, in our applications. This way, we don't have to introduce clipboardy, fs-extra nor meaow as dependencies in our projects either, so perhaps it is for the best, yes.
